---
- name: Update root password localhost
  mysql_user:
    name: "{{ mariadb_user_root }}"
    host: localhost
    password: "{{ mariadb_root_password }}"
    state: present
    check_implicit_admin: "yes"
    login_user: "{{ mariadb_user_root }}"
    login_host: localhost
    login_password: "{{ mariadb_root_password }}"
#
- name: Update root password all hosts
  mysql_user:
    name: "{{ mariadb_user_root }}"
    host: "{{ item }}"
    password: "{{ mariadb_root_password }}"
    state: present
    login_user: "{{ mariadb_user_root }}"
    login_host: localhost
    login_password: "{{ mariadb_root_password }}"
  loop:
    - "::1"
    - "127.0.0.1"
    - "{{ ansible_fqdn }}"
    - "{{ ansible_hostname }}"
  when: ansible_hostname != 'localhost'
#
- name: Remove Anonymous users
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: "{{ mariadb_user_root }}"
    login_password: "{{ mariadb_root_password }}"
#
- name: Remove the test Database
  mysql_db:
    name: test
    state: absent
    login_user: "{{ mariadb_user_root }}"
    login_password: "{{ mariadb_root_password }}"
  notify: mariadb restart
...
