---
- name: Create Red Hat MariaDB repo
  yum_repository:
    name: mariadb
    description: MariaDB repo
    baseurl: "{{ mariadb_repo }}"
    gpgkey: "{{ mariadb_gpgkey }}"
    gpgcheck: yes
    enabled: yes
...
